# Generated by Django 4.2.11 on 2024-03-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_loginuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='email',
            field=models.CharField(default=False, max_length=255, verbose_name='이메일 주소'),
        ),
    ]
