# Generated by Django 4.2.11 on 2024-03-18 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_doit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 8, 13, 38, 9152, tzinfo=datetime.timezone.utc), verbose_name='시작날짜'),
        ),
    ]
